### ISSUE TITLE
Integrate with `optimism-package`

### ISSUE THREAD

**Issue by MegaRedHand** [Layr-Labs/avs-devnet#122]
We should use [optimism-package](https://github.com/ethpandaops/optimism-package) to support deploying an Optimism L2. This would serve for testing any application that interacts with L2s.

**Comment by samlaf** [comment]
This would be awesome! I just added altda support to optimism-package in https://github.com/ethpandaops/optimism-package/pull/154, and using it to spin up an op-package that targets our eigenda testnet. Would be awesome to make it work with your local eigenda example.

Tried it out with the v1, it worked for a while but faced some issues, so would be more interested in making this work with v2 devnet.

**Comment by samlaf** [comment]
One thing to keep in mind is that both op-package and avs-devnet spin up an ethereum-package. However, op-package is setup to be able to point to an external L1 instead of deploying its own using ethereum-package. So what you can do is change the ethereum_package in avs-devnet to add an additional_preloaded_contracts (which op-deployer requires):
```
ethereum_package:
  additional_services:
    - blockscout
  network_params:
    # NOTE: turning this to 1s causes "referenceBlockNumber is in future" errors
    seconds_per_slot: 3
    additional_preloaded_contracts: '
      {
        "0x4e59b44847b379578588920cA78FbF26c0B4956C": {
          "balance": "0ETH",
          "code": "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3",
          "storage": {},
          "nonce": "1"
        }
      }
    '
```

And then you can change the op's yaml config to use
```
external_l1_network_params:
  network_id: "3151908"
  rpc_kind: standard
  el_rpc_url: http://el-1-besu-lighthouse:8545
  el_ws_url: ws://el-1-besu-lighthouse:8546
  cl_rpc_url: http://cl-1-lighthouse-besu:4000
  priv_key: "04b9f63ecf84210c5366c66d68fa1f5da1fa4f634fad6dfc86178e4d79ff9e59"
```
instead of ethereum_package.
